### ISSUE TITLE
Bug in the last life

### ISSUE THREAD

**Issue by felipevcc** [Andres98100/2035-logica-programacion-2-Aula1#1]
## Bug description

The application takes guessing the number in the last life as a defeat. It shows that the user lost the game with the message "Se han agotado las vidas". It should appear that the user won the game.

## Screenshot

![Captura de pantalla 2024-01-20 013420](https://github.com/Andres98100/2035-logica-programacion-2-Aula1/assets/95534180/0fb695b6-b290-4f64-abfb-aba6d9ee1af0)

**Comment by Andres98100** [comment]
ok, thanks for your observation, the bug has been resolved and the game behaves normally
